### ISSUE TITLE
Unable to read Geo location

### ISSUE THREAD

**Issue by jacklu333333** [stm32duino/X-NUCLEO-GNSS1A1#12]
Hi, 
I use the stm32F401re board with the GNSS 1A1 module with the sample code of UART. However, the reading value from the board of all metrics is none or zero. Further, the altitude is always 100m.
Does anyone have a similar problem or solution?
Thanks in advance.

**Comment by cparata** [comment]
Hi @jacklu333333 ,
did you test the example outdoor? The GNSS module works only outdoor and normally at the first try it takes a while (few minutes) to fix the coordinates of all the satellites. After the first time it should be faster to hook the signal of the satellites. Please, check also that the antenna is well connected at the shield.
Best Regards,
Carlo

**Comment by jacklu333333** [comment]
Yes, we do tried but not on the shield. And we put the antenna out the window for more than ten minutes, that's why we exclude the possibility of connection problem. Also, during the test, we use mobile to get the data for reference. Unfortunately, still no data is read.

**Comment by cparata** [comment]
Hi @jacklu333333 ,
thanks for the response. I will do some tests on my side in the next days and I let you know.
Best Regards,
Carlo

**Comment by cparata** [comment]
Hi @jacklu333333 ,
could you share with me how did you set the jumpers in your shield? In order to use the Nucleo-F401 and the GNSS shield with UART connectivity you need to set on your shield J2, J5, J7, J8, J10, Opened and J3, J4, J6, J9, J11, J12, J13 Closed. Could you also test the I2C sketch in order to see if your shield  works at least with I2C interface?
Best Regards,
Carlo

**Comment by jacklu333333** [comment]
I check again the jumpers, and it is the same as what you wrote. I will try the I2C interface later. If the I2C interface also doesn't work, does it mean the shield is broken? Or what might be the reason? Thanks.

**Comment by cparata** [comment]
Basically, I tested all the sketches in the library with both UART and I2C with my shield and I'm able to read the geo coordinates in all cases. Are you running the HelloWorld example or the NMEA example? In the first case, you can check if at least you are able to read the firmware version of the GNSS module; basically, open the Arduino Monitor and when the menu appears, you can type 8 and press Enter and then you can copy the first string that appears and press enter again. In this way, if the communication with the module is working you should see the firmware version of the GNSS module, otherwise you will see a communication error.
Best Regards,
Carlo

**Comment by jacklu333333** [comment]
Yes, I can see the firmware version of the module. There is no error and this is the firmware version GNSSLIB_8.4.10.16.3_ARM. Still, I can not read the GNSS data. Is there any other possibility for this situation? Thanks

**Comment by cparata** [comment]
Ok, this is the same version that I have on my shield. If you are able to read this information, it means that the GNSS module and the MCU are able to communicate correctly. The only reason that I can find, it is that the GNSS antenna is not really in an outdoor environment. Take into account that mobile phone combines GNSS signal with LTE/GSM info to get the position also in an indoor environment. In order to understand if the antenna of the shield is getting a good GNSS signal, I suggest you this experiment: put your mobile phone offline and then activates geo-localization in an indoor environment.  If you open Google Maps on your phone, you will see that after a while the position will be grey because there is no LTE/GSM signal (your phone is offline) and the GNSS signal is poor (because you are indoor). Now you can put the mobile phone (always in offline mode and only geo-localization enabled) close to the antenna in your outdoor setup. If the position on Google Maps remains grey, it means that the GNSS signal is still poor and so you need to find a better outdoor location for the antenna of the shield; instead if the position on Google Maps becomes blue, it means that the GNSS signal is good and so you have some troubles on your shield. Let me know the outcomes of this experiment.
Best Regards,
Carlo

**Comment by cparata** [comment]
Hi @jacklu333333 ,
do you have any update?
Best Regards,
Carlo

**Comment by jacklu333333** [comment]
Due to there is no other possibility, I give the GNSS another shot with the same location and setup. Then it suddenly works. The only difference is that the module keeps on for over four hours in advance before the experiment and the weather is different, which is better than previous times. 
Sorry for bothering you with this problem, I couldn't give a proper explanation to this suituation. Until now, I still don't know why it didn't work previously.

**Comment by cparata** [comment]
Ok, anyway I guess that we can close this ticket
